// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AiPlatformRadioGroup: typeof import('./src/components/AiPlatformRadioGroup.vue')['default']
    AiSelect: typeof import('./src/components/AiSelect.vue')['default']
    BaseWebview: typeof import('./src/components/BaseWebview.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DuelWebview: typeof import('./src/components/DuelWebview.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmojiLogo: typeof import('./src/components/EmojiLogo.vue')['default']
    FullScreenButton: typeof import('./src/components/FullScreenButton.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    MarkdownMap: typeof import('./src/components/MarkdownMap.vue')['default']
    PaginationScrollbar: typeof import('./src/components/PaginationScrollbar.vue')['default']
    PromptInput: typeof import('./src/components/PromptInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tip: typeof import('./src/components/Tip.vue')['default']
    Window: typeof import('./src/components/window/Window.vue')['default']
    WindowTitleBar: typeof import('./src/components/window/WindowTitleBar.vue')['default']
  }
}
